src/main/kotlin/com/charleskorn/kaml/Yaml.kt, src/main/kotlin/com/charleskorn/kaml/YamlInput.kt, src/main/kotlin/com/charleskorn/kaml/YamlNode.kt, src/main/kotlin/com/charleskorn/kaml/YamlNodeReader.kt, src/main/kotlin/com/charleskorn/kaml/YamlOutput.kt, src/test/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/test/kotlin/com/charleskorn/kaml/YamlSealedTest.kt, src/test/kotlin/com/charleskorn/kaml/YamlTaggedTest.kt, src/test/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/test/kotlin/com/charleskorn/kaml/testobjects/TestObjects.kt
- implement #4 
- support yaml tags for polymorphic de-/serialization
=> Support tagged nodes

build.gradle.kts, src/main/kotlin/com/charleskorn/kaml/Yaml.kt, src/main/kotlin/com/charleskorn/kaml/YamlInput.kt, src/main/kotlin/com/charleskorn/kaml/YamlOutput.kt, src/test/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/test/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/test/kotlin/com/charleskorn/kaml/testobjects/PolymorphicTestObjects.kt
- Use {type}.serializer() method instead of {type}Serializer class
- Use list and nullable extension property in builtin package
- Use MapSerializer class instead of map extension property
- Use object to serialize kotlin.Unit
- Use AbstractEncoder/Decoder instead of ElementValueEncoder/Decoder
- Implement decodeElementIndex in AbstractDecoder
- Change parameter name of implemented method to match with super method
=> Migrate to kotlin 1.3.70 and kotlinx-serialization 0.20.0

src/main/kotlin/com/charleskorn/kaml/YamlConfiguration.kt, src/main/kotlin/com/charleskorn/kaml/YamlOutput.kt, src/test/kotlin/com/charleskorn/kaml/YamlWritingTest.kt
This adds support for the Flow Style of rendering Sequences, by adding a parameter to `YamlConfiguration`
The default block style is still used to avoid breaking anything.
This is referenced in #33
=> Add support for different flow styles in Sequences

src/main/kotlin/com/charleskorn/kaml/YamlConfiguration.kt, src/main/kotlin/com/charleskorn/kaml/YamlInput.kt, src/main/kotlin/com/charleskorn/kaml/YamlOutput.kt, src/test/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/test/kotlin/com/charleskorn/kaml/YamlWritingTest.kt
I'm sorry for the sudden PR.
For personal reasons, I created a polymorphic key that can be changed to something other than "type", such as the `classDiscriminator` option in` kotlinx.serialization.json.Json`.
If this proposal is accepted, I would be grateful if you could incorporate it into the main branch.
=> Support custom polymorphic key

src/commonMain/kotlin/com/charleskorn/kaml/YamlNode.kt
My use case involves a big file with a top level map with a bit over 40 thousand keys. Parsing it took two minutes on my laptop. After my changes parsing time went down to 10 seconds.
=> Make faster duplicate keys checking

src/jvmMain/kotlin/com/charleskorn/kaml/Yaml.kt, src/jvmTest/kotlin/com/charleskorn/kaml/JvmYamlReadingTest.kt, src/jvmTest/kotlin/com/charleskorn/kaml/JvmYamlWritingTest.kt
Fixes #246.
Note that this was done via GitHub's web interface, so this exact change is untested. I have tested the `decodeFromStream` extension function locally in a downstream project, though.
The implementation (along with the KDoc comments) mirrors the one in [kotlinx.serialization.SerialFormat](https://github.com/Kotlin/kotlinx.serialization/blob/v1.3.2/core/commonMain/src/kotlinx/serialization/SerialFormat.kt#L84-L97).
=> Add generic `decodeFromStream`/`encodeToStream` extension functions

src/commonMain/kotlin/com/charleskorn/kaml/YamlComment.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlConfiguration.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/jvmMain/kotlin/com/charleskorn/kaml/YamlOutput.kt
Hi. I've created an annotation to add comments for properties on serialization. This PR could be improved so I'm waiting for any suggestions (or PR rejection)
Some questions:
- Should `@YamlComment` annotation be marked as `@ExperimentalSerializationApi`?
- Do you want configuration value to disable comment serialization?
- Are tests good enough or there should be more?
P.s.: Edits by maintainers should be allowed too
=> Added experimental comment support on serialization

src/commonMain/kotlin/com/charleskorn/kaml/YamlConfiguration.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/jvmMain/kotlin/com/charleskorn/kaml/YamlOutput.kt
There was previously no configurable indent for sequences. This pr enables this functionality
Previously
```yaml
list:
- 1
- 2
- 3
```
Now with `sequenceBlockIndent` set to `2` (default `0` to preserve backwards compatibility)
```yaml
list:
- 1
- 2
- 3
```
=> Add a configurable indent for sequences

README.md
* https://bitbucket.org/asomov/snakeyaml-engine consists of only an outdated wiki (see the "Changes" page there, it lists v2.3 from last year as latest version).
* https://bitbucket.org/snakeyaml/snakeyaml-engine has the source code, issues and an up-to-date wiki. I linked to the wiki home page directly, as it's not very discoverable from the repository home page.
=> Update SnakeYAML repository URL

src/commonMain/kotlin/com/charleskorn/kaml/Yaml.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlContextualInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlListInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlMapInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlMapLikeInputBase.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlNullInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlObjectInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlPolymorphicInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlScalarInput.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/jvmMain/kotlin/com/charleskorn/kaml/Yaml.kt
This adds a method on `YamlInput` that allows for decoding a serializable value from a `YamlNode`. 
The use case for this kind of functionality is the ability to manually interpret the structure of a YAML document and then delegate the deserialization of `YamlNode`s to other serializer implementations.
For example, in the test case I added we have this document:
```yaml 
keyA:
host: A
keyB:
host: B
```
which is a map of `Database` objects. Perhaps we want to decode this as a `List<Database>` instead of a `Map<String, Database>` (because reasons) and this enables us to write a custom serializer that looks at each `YamlNode` entry on the `YamlMap` and then delegates the deserialization of each `Database` object to the `Database` serializer rather than having to manually decode the rest of …
=> Add decoding from YamlNode

src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/testobjects/TestObjects.kt
Hi @charleskorn 
I ran into some trouble when parsing an enum with explicit serial names into a config using Hoplite. Was trying to pinpoint the issue, and it seems it's not in KAML 🙂 If you feel there's any value to adding the tests you're welcome to merge this, otherwise just close it.
=> Adding test with named enum values

src/commonMain/kotlin/com/charleskorn/kaml/YamlConfiguration.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/jvmMain/kotlin/com/charleskorn/kaml/YamlOutput.kt
This pull request adds SingleLineStringStyle.PlainExceptAmbiguous that escapes Strings that would be a different type if they were not a String. Resolves #367.
For example, when SingleLineStringStyle is set to PlainExceptAmbiguous, "12" will become "12" in Yaml, whereas Plain would have it be 12.
I have also added an extra configuration option of ambiguousEscapeStyle so the user can choose the escape style for when the string is ambiguous. If it is set to SingleQuoted, then the above example would be escaped like '12', rather than "12". This defaults to DoubleQuoted.
The private function String.isAmbiguous() deems a String as not a String if it was not a String by parsing it as a Long, Double and Boolean. If it is none of these, then it is not ambiguous and we can leave it as plain.
I …
=> Add SingleLineStringStyle.PlainExceptAmbiguous and AmbiguousEscapeStyle

build.gradle.kts
- Since Kotlin 1.4.0, the [stdlib dependency is longer required](https://kotlinlang.org/docs/gradle-configure-project.html#dependency-on-the-standard-library), and is added automatically according to the source set and Kotlin plugin version:
- This means `stdlib-jvm` version 1.8.21 (the version of the Kotlin plugin) is automatically added anyway to the jvm source set.
- Since Kotlin 1.8.0, [stdlib-jdk8 has been merged into stdlib](https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target) because JDK 6 and JDK 7 are no longer targets.
- Version alignment is done automatically as above; the bom is only required if there are issues with this.
=> Remove unnecessary stdlib dependency

build.gradle.kts
In Kotlin 1.8.20, `kotlinOptions` was deprecated in favour of `compilerOptions`. This means there is type safety with specifying the JVM target now.
https://kotlinlang.org/docs/whatsnew1820.html
https://youtu.be/R1JpkpPzyBU?t=150
=> Replace kotlinOptions with compilerOptions

src/commonTest/kotlin/com/charleskorn/kaml/YamlExceptionTest.kt
https://github.com/charleskorn/kaml/issues/27#issuecomment-1540530440
Fully multiplatform tests can't be nested due to limitations in Javascript. This flattens YamlExceptionTest to describe itself as before but without any nesting.
If you're okay with these changes, I can do them for the other tests, with some refactactoring (splitting into smaller parts) to address https://github.com/charleskorn/kaml/issues/27
=> Flatten Yaml Exception Test

build.gradle.kts, src/commonTest/kotlin/com/charleskorn/kaml/YamlNodeTest.kt
https://github.com/charleskorn/kaml/issues/27#issuecomment-1540530440
I've replaced listOf with [withData](https://kotest.io/docs/framework/datatesting/data-driven-testing.html#getting-started) from Kotest's data test module. This creates a test for each piece of data.
=> Flatten Yaml Node Test

.github/workflows/build.yml
Java 18 is end-of-life. This pull request changes the build file to use Java 17 as that is the latest LTS release that has been built for Temurin. I would suggest upping this to Java 21 once Adoptium has created binaries for it and Kotlin supports Java 21.
=> Use Java 17 in build.yml

.github/workflows/build.yml
The [Gradle GitHub Action](https://github.com/gradle/gradle-build-action) automatically handles cache to do with Gradle and Gradle build files for you:
> ## [Caching build state between Jobs](https://github.com/gradle/gradle-build-action#caching-build-state-between-jobs)
> The `gradle-build-action` will use the GitHub Actions cache to save and restore reusable state that may be speed up a subsequent build invocation. This includes most content that is downloaded from the internet as part of a build, as well as expensive to create content like compiled build scripts, transformed Jar files, etc.
This also fixes the renovate issue that used a commit hash for actions/checkout v4 rather than a version number.
Also, may I ask why the build file uses specific version numbers? E.g. @4.1.0 rather …
=> Replace manual actions/cache with gradle action

README.md
Fix up typo - `Backend` and `Frontend` should both be of type `Server`
=> Fix typo in sealed class example

src/commonMain/kotlin/com/charleskorn/kaml/YamlConfiguration.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlInput.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/jsMain/kotlin/com/charleskorn/kaml/YamlOutput.kt, src/jvmMain/kotlin/com/charleskorn/kaml/YamlOutput.kt, src/jvmTest/kotlin/com/charleskorn/kaml/JvmYamlWritingTest.kt
This implements #378 by introducing a new `None` style that omits the tag/property entirely from the output yaml.
Note this is asymmetric and reads are treated the same as `Tag` as reads require a tag.
I added a few tests to JvmYamlWritingTest for both this case and some added coverage for the existing two cases as well.
=> Introduce PolymorphismStyle.None

README.md, build.gradle.kts, gradle.properties, kotlin-js-store/yarn.lock, src/commonTest/kotlin/com/charleskorn/kaml/TestUtils.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/jsTest/kotlin/com/charleskorn/kaml/TestUtils.kt, src/jvmTest/kotlin/com/charleskorn/kaml/TestUtils.kt, src/wasmJsTest/kotlin/com/charleskorn/kaml/TestUtils.kt
Part of https://github.com/charleskorn/kaml/issues/232
=> Add support for wasmJs

build.gradle.kts, kotlin-js-store/yarn.lock, src/commonTest/kotlin/com/charleskorn/kaml/FlatFunSpec.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlMapTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlPathTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlScalarTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt
Two changes were needed:
* I got help from the Kotlin team regarding running Wasm tests, it was about regenerating the Yarn lockfile by removing `build/js/yarn.lock` and then running the tests again: https://youtrack.jetbrains.com/issue/KT-68950/Wasm-test-task-fails-with-multiple-Could-not-write-XML-test-results-...#focus=Comments-27-9945807.0-0
* applied a workaround for the nested tests, suggested here: https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1718706660788649?thread_ts=1718703411.234529&cid=CT0G9SD7Z
JS tests still fail, mostly with `AssertionFailedError: expected:<NaN> but was:<NaN>`, so leaving them disabled.
=> Enable Wasm tests

build.gradle.kts, src/commonTest/kotlin/com/charleskorn/kaml/YamlScalarTest.kt
Hi, this PR allows running tests for JS targets.
The old version of tests had the following problems:
- It is incorrect to compare NaN to another NaN using `==` operator. For Java `Float.NaN == Float.NaN` returns `false` (but `Objects.equals(Float.NaN, Float.NaN)` returns `true `, which is why tests work for Java). For JS it is [a bit different](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN).
> NaN compares unequal (via [==](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality), [!=](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Inequality), [===](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality), and …
=> Update tests to run for JS targets

src/commonMain/kotlin/com/charleskorn/kaml/YamlInput.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt
Hi, @charleskorn.
This PR corrects how `YamlInput` handles the serialization of fields marked with `@Contextual` annotation.
Instead of forcing the serializer to call `beginStructure` it extracts the actual definition and creates the appropriate `YamlInput` based on that definition where applicable.
Please, take a look at the PR once you have time. Let me know if you have any remarks/suggestions regarding the change
Resolves #568
=> Correct handling of `SerialKind.CONTEXTUAL` in `YamlInput` class

src/commonMain/kotlin/com/charleskorn/kaml/Annotations.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlConfiguration.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlOutput.kt, src/jvmTest/kotlin/com/charleskorn/kaml/JvmYamlWritingTest.kt
A first draft of what I asked for in https://github.com/charleskorn/kaml/discussions/594
The main problem I faced is that the `fun encodeString(value: String)` as defined by Kotlin does not pass the descriptor and index.
So this first attempt works (on my machine) but does make that `this will not work in a multithreaded situation` and multiple yamls are written at the same time by the same instance.
So either that problem can be fixed in a different way or it is essentially impossible to build.
=> feat(JVM): Annotations to set the ScalarStyle on a single field.

src/commonMain/kotlin/com/charleskorn/kaml/YamlContextualInput.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/testobjects/PolymorphicTestObjects.kt
Second bug from https://github.com/charleskorn/kaml/pull/607 (as preparation for the PR)
> Previously it was not possible to implement a content based polymorphic serializer in the case that one of the types involved is a scalar. Different from the JSON serialization library it was therefore impossible to implement something like:
```yaml
myCats:
myFirstCat: "Bella"
mySecondCat:
name: "Daisy"
age: 2
```
```kotlin
typealias MyCats = Map<String, CatDetails>
@Serializable(with = MyContentBasedSerializer::class)
sealed interface CatDetails {
@Serializable
value class InlineName(val name: String) : CatDetails
@Serializable
data class More(
val name: String,
val age: String?
) : CatDetails
}
object MyContentBasedSerializer : YamlContentPolymorphicSerializer<CatDetails>(CatDetails::class) { …
```
=> Prepare fix for contextual deserialization of polymorphic scalars

src/commonMain/kotlin/com/charleskorn/kaml/Yaml.kt
This is a fixup for 45a455c400cef16868070da7c0ac283dba08ebbe.
=> fix: use serializers from the module in `decodeFromYamlNode`

src/commonMain/kotlin/com/charleskorn/kaml/YamlListInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlMapLikeInputBase.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt
First bug from https://github.com/charleskorn/kaml/pull/607
> Previously the `node` property on the decoders was not traversed in deep YAML trees (e.g. with `YamlMapLikeInputBase` and `YamlListInput`). This behaviour is different from the JSON serialization library and makes it impossible to implement a content based polymorphic `KSerializer` in a meaningful way without knowing of the whole YAML tree. See also the `DecodingFromYamlNodeSerializer` in `YamlReadingTest.kt` for an affected case
=> fix: `Decoder` does not represent the current node correctly

src/commonMain/kotlin/com/charleskorn/kaml/YamlInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlNode.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlNodeSerializer.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlNullInput.kt, src/commonMain/kotlin/com/charleskorn/kaml/YamlPolymorphicInput.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlNullReadingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlScalarReadingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt, src/commonTest/kotlin/com/charleskorn/kaml/testobjects/TestObjects.kt
=> feat: Make Yaml nodes serializable

build.gradle.kts, kotlin-js-store/yarn.lock, settings.gradle.kts, src/commonTest/kotlin/com/charleskorn/kaml/YamlScalarTest.kt
It's actually https://github.com/charleskorn/kaml/pull/646, but with a workaround for an issue related to coroutines in the tests.
=> deps: update Kotlin to 2.1.0
